### ISSUE TITLE
Game is too bright, even with the lowest value

### ISSUE THREAD

**Issue by Phraqzy** [Novum/vkQuake#161]
I can't lower contrast and brightness, the lowest values looks like this
![image](https://user-images.githubusercontent.com/43043436/51443729-aba6f180-1cd4-11e9-8052-ebd01539209a.png)
![image](https://user-images.githubusercontent.com/43043436/51443753-e3ae3480-1cd4-11e9-9615-f80b87ad59b1.png)
This problem does not occour with Quakespasm, the colors are smooth: 
![image](https://user-images.githubusercontent.com/43043436/51443783-4f909d00-1cd5-11e9-82d6-8713bf364941.png)
I'm using Radeon with Mesa drivers

**Comment by Novum** [comment]
Something is seriously wrong with your display gamma. vkQuake uses the same shader tone mapping as QuakeSpasm.

**Comment by brzegorz** [comment]
I'd like to bump this thread, as I have exactly the same issue. I also use the mesa drivers with RX 570 on Arch Linux. I use the build from AUR(https://aur.archlinux.org/packages/vkquake/). I doubt that it' system-wide, as vkquake is literally the only program suffering from the issue. But if you are right, how can I troubleshoot it?

**Comment by LethalManBoob** [comment]
If i can offer some advice. Make sure the vulkan sdk and runtime are updated with the newest drivers when building them. And if you dont build, try building it.

**Comment by ckotte** [comment]
@Phraqzy @brzegorz Could you resolve this issue in the meantime? I have the same issue with Arch Linux and vkquake or vkquake-git from AUR. However, I use the Intel vulkan drivers.

**Comment by dreamer** [comment]
I am also experiencing this issue; my Vulkan libs are up-to-date, using RX590.

**Comment by ckotte** [comment]
Looks like this is at least a valid workaround. If I set ```gamma``` to ```2```, then it looks similar to quakespasm. If I change the brightness slider in the game it resets immediately and the display is too bright again.

I have a slightly different output:
```
Using A2B10G10R10 color buffer format
Using X8_D24 depth buffer format
```

**Comment by Faalagorn** [comment]
I've tested that on two computers (both with Arch and pretty much the same configuration other than the GPU, drivers and some installed software such as WM/DE).

Here's how it looks at my RX 580 with Mesa (Mesa 19.2.0-devel (git-a0a7fa7531) with ACO)
![Screenshot from 2019-08-16 19-51-18](https://user-images.githubusercontent.com/4951331/63189307-f8348e80-c063-11e9-97d5-e680e4a54ce6.png)
![Screenshot from 2019-08-16 19-51-12](https://user-images.githubusercontent.com/4951331/63189308-f8cd2500-c063-11e9-832e-7ce4a134bd2a.png)

And here's how it looks on Nvidia 960 (nvidia 430.40)
![quake_max](https://user-images.githubusercontent.com/4951331/63189330-05517d80-c064-11e9-986d-60a41e561907.png)
![quake_min](https://user-images.githubusercontent.com/4951331/63189329-04b8e700-c064-11e9-9e78-a2218e3cc17f.png)

**Comment by davll** [comment]
I don't think that incorrect display settings cause the problem because Quakespasm is not too bright as vkQuake.

Quakespasm without sRGB color space (original code)
![2020-02-11-004616_1920x1080_scrot](https://user-images.githubusercontent.com/485491/74172485-491bed00-4c6b-11ea-817b-4179d501f559.png)

However, the modified Quakespasm with sRGB output enabled can reproduce the same issue.

Quakespasm with sRGB color space enabled (modified code)
![2020-02-11-010602_1920x1080_scrot](https://user-images.githubusercontent.com/485491/74172525-5d5fea00-4c6b-11ea-95bc-5a2fabdab1b3.png)

So, the root cause of the problem is that sRGB pixel format will convert the outputs of fragment shaders by `y = pow(x, 1/2.2)` to preserve more details on dark areas. However, original Quake and GLQuake do rendering on sRGB space already (there was no idea about gamma correction...) so it will result in over-bright views due to unnecessary encoding operations on sRGB.

To fix the problem on vkQuake is easy:
Set the format of swap chain images and image views to `VK_FORMAT_B8G8R8A8_UNORM` to avoid sRGB encoding operation.

The problem disappeared!!
![2020-02-11-013100_1920x1080_scrot](https://user-images.githubusercontent.com/485491/74174040-33f48d80-4c6e-11ea-87b2-9896b9d5c0e8.png)

I will submit a pull request to fix the problem
