### ISSUE TITLE
Particles appear as right-angled triangles if rendered at a distance.

### ISSUE THREAD

**Issue by Swallagoon** [Novum/vkQuake#194]
With my PC on the GTX 1080, it always renders the distant particles as triangles no matter the video settings I use.

(On a side note specifically for integrated Intel graphics 615: anisotropic filtering actually forces linear texture filtering on everything preventing the ability to have nearest neighbour + anisotropic on at the same time. Even the menu/HUD/console incorrectly has linear filtering applied to it. Intel graphics isn't so hot with Vulkan.)

Win10 w. latest drivers etc.

Screenshot is from Halloween Jam 2 - Misadventure Galley

![2019_11_10_00_47_22_vkquake0080 png_336_Layer_1_RGB_8_](https://user-images.githubusercontent.com/32944138/68537073-1b669580-0356-11ea-8c9d-1f42a58ee872.jpg)

**Comment by Rikoshet-234** [comment]
yea, i have that problen too. when i shot monsters or something else, i give that strange triangles on the distance instead of circles. and it not depends what fov you use

**Comment by Novum** [comment]
This is the original behavior of glQuake too. It's drawing one triangle instead of two for each quad. When I ported from QuakeSpasm I used that path because it was easier. Will fix it at some point.

**Comment by Novum** [comment]
ad3588e37e32d9423697d51922dbf89780a3313a
![image](https://user-images.githubusercontent.com/112222/69895723-f2a14280-12fa-11ea-87aa-147bea56d849.png)

**Comment by Rikoshet-234** [comment]
![spasm0000](https://user-images.githubusercontent.com/34555340/71323054-5b7d7400-24cf-11ea-96e1-031d79b25550.png)
![spasm0001](https://user-images.githubusercontent.com/34555340/71323055-5b7d7400-24cf-11ea-9985-c425cf4ef5d5.png)
unfortunately the problem is not completely solved, this is what quakespasm looks like
![vkquake0003](https://user-images.githubusercontent.com/34555340/71323076-8f589980-24cf-11ea-80d5-4351660fec35.png)
![vkquake0000](https://user-images.githubusercontent.com/34555340/71323078-92538a00-24cf-11ea-869c-ca5764d4ae24.png)
and thats vkQuake

**Comment by Rikoshet-234** [comment]
looks like a problem with alpha blending in the shader

**Comment by Rikoshet-234** [comment]
because quakespasm looks absolutely normaly when r_quadparticles set to 0
