### ISSUE TITLE
z-fighting fix?

### ISSUE THREAD

**Issue by Hexaae** [Novum/vkQuake#245]
Is there a way to fix z-fighting in some locations, like this?
![vkquake0001](https://user-images.githubusercontent.com/8591462/96099016-1188d300-0ed3-11eb-99b5-d07b5db23055.png)

**Comment by Novum** [comment]
Same happens in glQuake.

**Comment by LethalManBoob** [comment]
gl_zfix 1?
Btw gl_zfix is not 1 by default but the shadows in the first level left of the first explosive crate are clipping and only work properly with gl_zfix 1. This has been an issue for me since ever.

**Comment by mjr4077au** [comment]
`gl_zfix` can also reveal secrets as well so it's an imperfect fix. Are you playing with the -fitz argument by chance? This skips loading of quakespasm/vkquake.pk3 which has patches for default Quake maps to fix the z-fighting without the drawbacks of the CVAR.

**Comment by LethalManBoob** [comment]
damn, i want that intro video :P

**Comment by mjr4077au** [comment]
Both projects would probably get a lot less bug reports if they just played the demo reel. So many think `-fitz` is just synonymous for "don't play demos" and run the game with it, but that switch does a lot of other things, not so good things...

**Comment by Hexaae** [comment]
> Are you playing with the -fitz argument by chance? This skips loading of quakespasm/vkquake.pk3 which has patches for default Quake maps to fix the z-fighting without the drawbacks of the CVAR.

No. But gl_zfix 1 didn't completely fix z-fighting here and there from certain angles & distance.

**Comment by mjr4077au** [comment]
> No. But gl_zfix 1 didn't completely fix z-fighting here and there from certain angles & distance.
The seams around secret passages etc are the drawbacks I mention, which is why I don't like using it.

First party content should be covered by the patches in the pk3 file. Mind you, I'm not sure the pk3 has patches for the expansions as I've seen z-fighting issues in Scourge of Armagon.

My understanding is the issue is essentially unfixable and are considered mapping issues. This conclusion was reached some time ago in the community. Rendering on hardware vs. software are rather different and I believe mappers making expansions position things appropriately for hardware rendering.

Quake isn't alone here. It's impossible to place sprites properly in GZDoom's hardware renderer. I've also been working on Raze (Build Engine source port) and there's a number of texture depth issues there in Polymost vs. software rendering.
