### ISSUE TITLE
[Feature request] quakespasm spiked advanced particles

### ISSUE THREAD

**Issue by Riccardoman** [Novum/vkQuake#258]
I've recently played arcane dimension 1.8 on QSS and I noticed that in vkquake the the advanced particle effects aren't present (like smoke and "rays")
Could you add support for them in vkquake?

**Comment by Novum** [comment]
I really don't like them and the code is a mess.

**Comment by BreakPoints** [comment]
Came to the issues section to request this and found that it had already been requested.

Would it be agreeable to mark this as open if you are open to the feature being added to increase visibility?

**Comment by Novum** [comment]
I don't like that there is no good way to disable them in the menu. I think they go beyond the vanilla Quake look that vkQuake is aiming for.

**Comment by BreakPoints** [comment]
That is reasonable, if it were to be added a toggle would definitely be required. I have requested that the QSS particle system have a menu toggle added upstream to QSS. [Link here](https://github.com/Shpoike/Quakespasm/issues/51)

As for it being a pain to implement, I understand. A lot of work for something you're not personally interested in which is why the exposure of an open issue may help somewhat. Maybe an AD fan with Vulkan knowledge will pick this up in the future.

**Comment by vide0hanz** [comment]
Hm, appears they are not interested in making that change either.

Perhaps it would be a good compromise to enable this via the console as needed? Then it is up to the mod dev to document accordingly if they take advantage of enhanced particles, etc.

**Comment by Novum** [comment]
@vide0hanz Who is "they"?

**Comment by vide0hanz** [comment]
> @vide0hanz Who is "they"?

@Shpoike - per the ticket that was linked earlier.

**Comment by Vagankovo** [comment]
Now that advanced particle effects are in vkQuake, shouldn't this issue be closed?

**Comment by sezero** [comment]
OK, closed.
