### ISSUE TITLE
[Feature request] Level menu, demo menu and mouse support

### ISSUE THREAD

**Issue by Riccardoman** [Novum/vkQuake#264]
Are there any chances to see levels and demos menu sections, and also menu mouse support implemented like in Mark V?

**Comment by rampancy777** [comment]
it would be really cool to be able to do basic file browsing in the console like dir. might be easier idk. just a list that we can scroll through.

**Comment by dumptruckDS** [comment]
@Novum There was a version of Quakespasm that was included with an earlier version of Arcane Dimensions that had some of the features listed above. They were not merged into the main for QS. I will try and find the source. Not having luck ATM.

**Comment by dumptruckDS** [comment]
Found it. I deleted some dead links in the quote below. I have this release and can find the menu graphic for you that used to be available.

Source code: 
https://github.com/ericwa/Quakespasm/tree/admod (commit e43a383)

> Quakespasm 0.92.2-admod
=======================

No stable releases of Quake engines as of June 2017 run ad_sepulcher.
This is the latest unreleased QuakeSpasm (r1411) with some extra changes:

- MAX_MAP_LEAFS raised to 100K
- A "mods" submenu in the main menu, with menu graphics (SimonOC)
- The "game" console command automatically execs quake.rc

Other notable things in SVN r1411 since the last release 0.92.1:

- static entities limit raised to 4096
- r_scale cvar for pixellated graphics

Source code: 
https://github.com/ericwa/Quakespasm/tree/admod (commit e43a383)

QuakeSpasm 0.92.2-qss-r7-admod
==============================

This is a customized build of QuakeSpasm-Spike r7 with changes from 
0.92.2-admod.

Use this engine if you want high-res replacement particles and weather effects.

For more information, check Spike's original package at:
http://triptohell.info/moodles/qss/quakespasm-spike-r7.zip

Source code:
https://github.com/ericwa/Quakespasm/tree/qss-r7-admod  (commit 9bd8eda)

EricW, June 2017
ewasylishen@gmail.com

**Comment by Riccardoman** [comment]
Not interested in a DRM release, I already own it but never used it

**Comment by Novum** [comment]
Considering this done. Demo menu isn't on my todo list.
