### ISSUE TITLE
Corrupted menu graphic with custom game

### ISSUE THREAD

**Issue by vsonnier** [Novum/vkQuake#275]
On current master `6d8858b317c84274c298eb107d0a966729d8e1e6 Fix crash in TexMgr_ReloadImage if texture was not loaded before` when loading a custom game save, like for Travail : https://www.quaddicted.com/reviews/travail.html
I got a corrupted Quake logo in the menu, with the console spitting:
```c
TexMgr_FreeTexture : not found
TexMgr_FreeTexture : not found
```
Command line : `-particles 10000 -protocol 999 -game travail +map start`

Screenshot:

![Corrupted_Logo_cr](https://user-images.githubusercontent.com/5152742/103474525-26278980-4da5-11eb-8d23-68c4f9aa84ca.png)

Save : 
[s0.zip](https://github.com/Novum/vkQuake/files/5761345/s0.zip)

If I revert 
```c
6d8858b317c84274c298eb107d0a966729d8e1e6 Fix crash in TexMgr_ReloadImage if texture was not loaded before
13ca479edb5ba5f8e53d26bec435458a79363ed3  Fix leaks in R_TranslateNewPlayerSkin and TexMgr_ReloadImage.
```
the corruption goes away.

**Comment by vsonnier** [comment]
Context : x64 binary compiled with latest VS 2019, running on Windows10 x64

Using either:
- Nvidia GTX 1050Ti Mobile with driver  460.89
- Intel HD 630 driver Version: 27.20.100.9079

give the same results.

**Comment by rsfb** [comment]
As mentioned [here](https://github.com/Novum/vkQuake/commit/6d8858b317c84274c298eb107d0a966729d8e1e6#comments), the [Omicron bots](https://web.archive.org/web/20190319182017/https://mrelusive.com/oldprojects/obots/obots.html) also show weird behaviour at that commit.

Question: Do you see a crash if you only revert 6d8858b317c84274c298eb107d0a966729d8e1e6 ?

In [pull request 274](https://github.com/Novum/vkQuake/pull/274), Alex mentioned seeing some crashes without that fix, which I haven't observed myself yet. Alex do you happen do you have a repro for these crashes?

My current guess is that the leak fix needs refining in a different way in order to be robust to all possible usage of `TexMgr_ReloadImage`.

**Comment by vsonnier** [comment]
> Question: Do you see a crash (or any other issue) if you only revert 6d8858b ?

Indeed if I only revert 6d8858b317c84274c298eb107d0a966729d8e1e6, the corruption is no longer present in my example.

**Comment by Novum** [comment]
Okay, I'm going to revert those changes until further investigation what the proper fix is.

**Comment by rsfb** [comment]
Makes sense! I opened #277 for the original issue that motivated the first commit.
