### ISSUE TITLE
Feature request: Separating FOV and viewmodel FOV

### ISSUE THREAD

**Issue by ZecChelovek** [Novum/vkQuake#281]
Not a big deal, but it'd be nice to have the fov at 110-120 without the weapons becoming elongated to hell and back. Though I'm sure this is more to do with Quakespasm, which probably means it's not something that will change until QS does first.

**Comment by ZecChelovek** [comment]
I found this in the Quake mapping discord vis-a-vis this subject:

`        if ((ent == &cl.viewent) && (cl_gun_fovscale.value) && (scr_fov.value != 0))
        {            
            if (scr_fov.value <= 90)
                scale = 1.0f;
            else
                scale = 1.0f / tan(DEG2RAD(scr_fov.value/2));//Phoenix
            glTranslatef(paliashdr->scale_origin[0]*scale, paliashdr->scale_origin[1], paliashdr->scale_origin[2]);
            glScalef(paliashdr->scale[0] * scale, paliashdr->scale[1], paliashdr->scale[2]);            
        }
    `

The user said it's old stuff from a website called quakesource.org, and that it should be no problem porting it to vulkan. Could something be done with it?

**Comment by andrei-drexler** [comment]
That code works perfectly, up to a point. After about fov 122 the model gets a bit too close to the camera and the grenade launcher starts clipping during the firing animation, for example. Screenshot with fov 130, to make it more obvious:
<img width="480" src="https://user-images.githubusercontent.com/5121829/131699863-be1f4af2-b970-4fe9-bb6f-5af7932444ef.jpg"/>
A minor issue, but it can be fixed by doing the opposite of what that code does: instead of scaling down the model on the X axis and bringing it closer to the camera, keep X unchanged and scale Y/Z and their offsets up by the same factor. Due to the way perspective works, this ends up looking the same, but without the clipping.

Anyway, some pics:

fov 90|fov 130 / cl_gun_fovscale 1|fov 130 / cl_gun_fovscale 0
---|---|---
<img width="240" src="https://user-images.githubusercontent.com/5121829/131713150-ceadef35-1fdd-499d-bd5c-41ea93cd0095.jpg"/>|<img width="240" src="https://user-images.githubusercontent.com/5121829/131713218-f5b0d73b-303c-4eba-b6cd-0f4435a37134.jpg"/>|<img width="240" src="https://user-images.githubusercontent.com/5121829/131713260-fdfe63a8-e53b-471d-8ce4-830b05f1530e.jpg"/>

https://github.com/Novum/vkQuake/commit/0c8b57908751f62aea37e268ea63fc98aa832b3b

**Comment by sezero** [comment]
@ericwa: do we want this patch is qs? (I'm not fond of it, but whatever.)

**Comment by Novum** [comment]
For what it's worth, all newer id games I worked on had a fixed FOV for guns too :)

**Comment by andrei-drexler** [comment]
BTW, @Novum, there are two more fov-related issues that I wanted to fix, but I thought I should check with you first:
1. fov doesn't have CVAR_ARCHIVE
2. with a high fov, and especially on an ultrawide monitor, if you stand right next to a wall you can partially see through it due to near-plane clipping
![vkquake0014](https://user-images.githubusercontent.com/5121829/131747665-ba327c4f-02b3-437b-a19f-0125e6b863ca.png)
I'd like to add two lines of code that would reduce the near plane distance when necessary. On a 16:9 monitor, the default value of 4 would still be used up until about fov 133, so this change would have no impact in most cases, only in those where it's really needed.
```diff
diff --git a/Quake/gl_rmain.c b/Quake/gl_rmain.c
index 2e70658..28c5b16 100644
--- a/Quake/gl_rmain.c
+++ b/Quake/gl_rmain.c
@@ -258,7 +258,8 @@ static void GL_FrustumMatrix(float matrix[16], float fovx, float fovy)
 	const float w = 1.0f / tanf(fovx * 0.5f);
 	const float h = 1.0f / tanf(fovy * 0.5f);
 
-	const float n = NEARCLIP;
+	const float d = 12.f * q_min(w, h);
+	const float n = CLAMP(0.5f, d, NEARCLIP);
 	const float f = gl_farclip.value;
 
 	memset(matrix, 0, 16 * sizeof(float));
```
Does this sound alright?

**Comment by ericwa** [comment]
> @ericwa: do we want this patch is qs? (I'm not fond of it, but whatever.)

Sounds useful for ultrawide monitors, or just cases when people want to try high FOV's

**Comment by sezero** [comment]
> > @ericwa: do we want this patch is qs? (I'm not fond of it, but whatever.)
> 
> Sounds useful for ultrawide monitors, or just cases when people want to try high FOV's

A backport patch, please

**Comment by andrei-drexler** [comment]
> A backport patch, please

[cl_fov_gunscale.txt](https://github.com/Novum/vkQuake/files/7100328/cl_fov_gunscale.txt)
[lower_nearclip_high_fov.txt](https://github.com/Novum/vkQuake/files/7100329/lower_nearclip_high_fov.txt)

**Comment by sezero** [comment]
Thanks!

**Comment by sezero** [comment]
The lower_nearclip patch isn't in vkquake yet?

**Comment by sezero** [comment]
The fovscale patch is in.

**Comment by andrei-drexler** [comment]
> The lower_nearclip patch isn't in vkquake yet?

It is now :)

**Comment by sezero** [comment]
I'll hold off the lower_nearclip patch for the moment, will possibly apply after release.

**Comment by andrei-drexler** [comment]
Alright.
