### ISSUE TITLE
Swinging blades in ad_lavatomb don't animate smoothly

### ISSUE THREAD

**Issue by Novum** [Novum/vkQuake#309]
Observed only with FTE protocol extensions. Also happening with QSS.

**Comment by andrei-drexler** [comment]
I've looked into this a bit. The swinging motion is achieved by [cycling](https://github.com/SimsOCallaghan/ArcaneDimensions/blob/320f1cec4545563e70027450f2d6d4f08f527c69/traps_pendulum.qc#L111-L185) back and forth through 13 different frames, and the jerkiness comes from the fact that the entity doesn't use the default think time of 0.1, but rather a [variable](https://github.com/SimsOCallaghan/ArcaneDimensions/blob/320f1cec4545563e70027450f2d6d4f08f527c69/traps_pendulum.qc#L105-L107) one based on the frame index. When the protocol extensions are disabled, the think interval is sent to the client so that frame lerping is done at the right speed.

https://github.com/Novum/vkQuake/blob/75f451a98c56ca2830afaa6e52185cfc7b989b19/Quake/sv_phys.c#L146-L155
https://github.com/Novum/vkQuake/blob/75f451a98c56ca2830afaa6e52185cfc7b989b19/Quake/sv_main.c#L1864
https://github.com/Novum/vkQuake/blob/75f451a98c56ca2830afaa6e52185cfc7b989b19/Quake/sv_main.c#L1926-L1927

The FTE protocol doesn't seem to support this, so client-side lerping is done as if the interval between frames were 0.1. I'm not sure what the right solution is, but it looks like it should probably be handled upstream.

P.S. Here's a custom map (with just a pendulum and a button) to make it easier to test this issue without having to play through ad_lavatomb: [pendulum.zip](https://github.com/Novum/vkQuake/files/6720856/pendulum.zip)
