### ISSUE TITLE
Text markup does not work as intended

### ISSUE THREAD

**Issue by p4thlight** [Novum/vkQuake#340]
Strings that begin with ^m for the brown tint are displayed as is in vk, whereas in QSS, they are displayed correctly. I understand the code to parse the Markup is in vk, but it doesn't appear to function correctly?
![quakespasm-spiked-win64_lkClSO9XPy](https://user-images.githubusercontent.com/88338281/128911212-36fb6b5d-097e-4c78-88dd-4b42946dd43e.png)
![vkQuake_ag9vCBWX1Z](https://user-images.githubusercontent.com/88338281/128911214-bd1b613c-1c61-41c2-9d22-2aee0e623046.png)

**Comment by Shpoike** [comment]
Markup parsing is also disabled in qss when using pr_checkextensions 0.

You can use "\sYour Red Text" in fteqcc/frikqcc instead, which will have the qcc mess around with those glyphs, which will work in every engine - except for those with utf-8 support enabled, because we don't care about any foreigners around here, or something (or at least have no suitable fonts and already have far too many incompatible mods/maps). The fact that you're using those [ ] glyphs already breaks utf-8 compat anyway so you might as well.

iirc, the other option is to prefix your individual prints with a "\x02". This will ask even the vanilla engine to recolour it for you (like it would with chat, but without playing the beep sound - use "\x01" if you want the beep sound for some reason).

**Comment by Novum** [comment]
Not supported. Not everything from QSS was merged and I don't intend to.
