### ISSUE TITLE
Malice "trigger in clipping list" crash

### ISSUE THREAD

**Issue by DefectiveByDesign** [Novum/vkQuake#362]
Malice "v2" crashes with trigger in clipping list. Not sure what's causing it. Pistol seems to trigger it.

Also, why has intensity been removed? I supposed the brightness control works ok, but quake does have issues with adjusting brightness, and the old idgamma commands work better at fixing it.

**Comment by Novum** [comment]
Please one bug report per issue.

**Comment by DefectiveByDesign** [comment]
https://www.moddb.com/mods/malice-for-quake-patched-with-bug-fixes-and-soundtrack/downloads

**Comment by Novum** [comment]
I ran this and it worked fine

**Comment by 77Mynameislol77** [comment]
I second this, i'm having the same issue, it started to happen about midway through my playthrough for some reason, i've attached a savegame where this happens.
[save.zip](https://github.com/Novum/vkQuake/files/8886206/save.zip)
.

**Comment by EdHerdman** [comment]
I just encountered this, again with the fan patch "Malice v2 fixed" from ModDB. This mod has weird behavior. Changing the contents of autoexec.bat gave me no mouse aiming on quickloading until I manually toggled mouse aim. The actual "trigger in clipping list" crash came when trying to rocket jump with the first explosive weapon in the game, which you get immediately after raising a bridge with a switch (in the first level after the training level). Attempting to fire any weapon from that savegame caused a crash.

This might be caused by whatever the fan patch is doing to enhance Malice. The original Malice replaces Quake's impulse 12 with a custom weapon reload function, per https://quakeone.com/forum/quake-help/general-help/8437-brute-force-weapon-scrolling-in-malice#post162002 and the fan patch seems to have added it back in, but impulse 12 still controls weapon reloads.

On the other hand, playing with the *original* Malice files works fine, except the flashlight seems to be missing. Perhaps there's also a conflict with the "y" key bringing up chat and also being used by Malice to switch "toys" (special equipment), but I haven't gotten that far yet.
