### ISSUE TITLE
Couple minor issues in mge4m2 from DotM

### ISSUE THREAD

**Issue by sezero** [Novum/vkQuake#367]
Reported to qs at https://github.com/sezero/quakespasm/issues/7 and is said to be present in vkquake too.

**Comment by mhQuake** [comment]
Is this a valid fix? Quake uses NULL surf->samples as a data saving trick for surfaces where the light would otherwise be 0. So having 0 light should actually be the correct behaviour.

**Comment by andrei-drexler** [comment]
You're right, not quite a valid fix on its own. The issue in DOTM is that there are multiple overlapping surfaces and sometimes the first one just happens to have no samples, but there are others that do have proper lighting info. I'll push another commit soon that will still skip the no-samples surfaces, but then only accept contributions from lit ones that are within a small distance (I'm thinking 8 units) of the initial hit. This still fixes the issues in DOTM, but has less potential to break in other situations.

**Comment by vide0hanz** [comment]
Testing lastest commit, noticing some objects in DOTM are still black, mostly noticable on the candles on the stairs throughout the new start hub:

![vkquake0000](https://user-images.githubusercontent.com/59800033/133108575-226819ac-d549-4f35-8fdf-7a22cb1496bc.png)

Also, I've been noticing other lighting quirks in this area. The center (altar?) area where the runes populate upon collecting them will appear to flicker at random, as if being lit by some nearby dynamic light source. I had to spam screenshot to capture this in action:

![vkquake0031](https://user-images.githubusercontent.com/59800033/133109048-a984ae56-1157-43db-aaf2-d910bfd6e9ef.png)

It can happen on this spinning geometry as well, albeit it seems to happen with less frequency since the most recent commits:

![vkquake0036](https://user-images.githubusercontent.com/59800033/133109960-c55b71f6-0ef2-46d2-8447-c1836a75b377.png)


Sorry if this is off topic, it seemed related to me.

**Comment by vide0hanz** [comment]
The same odd dynamic light behavior can be observed in vanilla Quake as well:

![vkquake0005](https://user-images.githubusercontent.com/59800033/133140762-d61ae328-dbdb-4617-b836-b315c0ed6d0c.png)

It may be hard to make out in the screenshot, but look at the light blob in the middle of the screenshot, on the right-side wall of the "normal" hallway, just to the bottom right of the gargoyle texture -- you can see the light from the lava ball sneaks through here. 

The interesting thing to note is that this only happens when the dynamic light source is in-frame. If you stand directly in the middle of the "normal" skill hallway, this no longer occurs. 

Its probably easier to notice in-game if you just load up the vanilla Quake start map and stand in the location of the screenshot. 

FWIW Quakespasm also has this behavior, but the affect is somewhat muted there.

I'm not sure if this is related to the issue or not, so my apoligies if this is irrelevant.

**Comment by andrei-drexler** [comment]
Those candles are black for a different reason - their origin is inside the stairs, and since the light trace only goes down from there, it doesn't hit any lit surface. That can be fixed pretty easily, too, by not tracing down from the origin, but rather from a higher point, maybe the top of the bounding box, or somewhere in-between. If you're compiling vkQuake yourself, you can try replacing
https://github.com/Novum/vkQuake/blob/52e490695a7b35e76cd17b53e57ea9f212470e4d/Quake/r_alias.c#L316
with
```c
	vec3_t		lpos;

	lpos[0] = e->origin[0];
	lpos[1] = e->origin[1];
	lpos[2] = e->origin[2] + e->model->maxs[2] * 0.5f;
	R_LightPoint (lpos);
```
and the candles will be fixed, too. At this point, though, it's starting to feel like we're piling on hacks to cover up design issues. It's not unheard of, but... do we want to? I'm not sure. Especially since some of those candles are black in the re-release, too...

As for the flickering altar, there's a fireball in there, but unlike the others this one is very short-lived. It spawns inside a solid, so it gets removed right away, along with its dynamic light. I haven't seen it in the re-release at all, but either way I'd call this a WNF. I'm not sure what's up with the spinning gears - they don't appear to have a fireball nearby, but I haven't spent much time looking into this one, either. It seems like such a small issue that it's probably not worth fixing when there are much more pressing concerns (like #359).

Edit: that dynamic light behavior in the start map is exactly the same as in vanilla Quake (either software-rasterized, or GLQuake with gl_flashblend 0). Not exactly impressive (or even correct) by today's standards, but at least it's faithful :)

**Comment by vide0hanz** [comment]
Thanks for the reply, that helps shed some light on whats going on. I was hesitant to even bring this stuff up since it seemed like byproducts of older rendering techniques, I've just never seen any mention of it elsewhere.

> As for the flickering altar, there's a fireball in there, but unlike the others this one is very short-lived. It spawns inside a solid, so it gets removed right away, along with its dynamic light. 

So this is just a fault in the map design. Same with the candles I'm gathering. I agree on calling this a WNF, this should be corrected in the map itself, if anything.

> I'm not sure what's up with the spinning gears - they don't appear to have a fireball nearby

Exactly, the nearest one is in the small lava pool in the center of the area directly in front of it; if you watch the fireball come up you can see it's dynamic light affects the spinning gears, which seem like they would be too far away to be affected by this. Sounds like another byproduct of the vanilla dynamic light behavior you mentioned.

As far as adding hacks to cover up design issues, thats a slippery slope and something that should probably be avoided unless trends in map design start to highlight these minor issues (emphasis on minor). Just my opinion on the matter. For example, I only noticed this black geometry once more on a single health pickup in a dark corner of a map in Arcane Dimensions... so yeah. I would imagine the Kex engine also has some other tricks up it's sleeve to mask these minor details that vkQuake and QS/QSS do not. 

I'll still try your suggestion to see if it improves things though. I never noticed the black candles in the Kex engine as well but I wasn't exactly looking for them there either :)

**Comment by Novum** [comment]
I'm pretty sure they did something like @andrei-drexler suggested, e.g. trace from the bounding box center. Would need to reverse engineer it by placing stuff in a map at different heights above the floor and then loading it into the remaster to find out.

Technically there is no "fault" if they assume that those maps only run with their new engine.

**Comment by vide0hanz** [comment]
@andrei-drexler just confirming that your suggestion works fine enough as-is for those candles, they are all rendered at a uniform brightness now. 

Though I think the Kex engine has other enhancements to the overall lighting system that complement this design choice, as some of the objects that are rendered pitch black in vkQuake appear to be rendered with indirect light in the Kex engine, and the effect is quite nice. 

So yeah, no "fault" here -- I  meant for that to be taken as "this is a product of the map design and not vkQuake". Its clear that a lot of the lighting enhancements are used to great effect in DOTM when played as it was intended. Its unrealistic to expect sourceports to re-implement this stuff, but perhaps a small change to account for design choices like this may not be a bad idea.

What do you think @Novum ?

**Comment by Novum** [comment]
I don't think it does, they read the same data files.

**Comment by mhQuake** [comment]
The Kex engine seems to build a Q3 style lightgrid at loadtime, going by evidence from the console log in the PC version. There is a minor optimization for lots of static entities where the lightpoint trace can be cached and reused, rather than tracing the BSP tree for each such entity that doesn't move. A lightgrid can satisfy this too.

**Comment by sezero** [comment]
Is the fix i.e. https://github.com/Novum/vkQuake/commit/52e490695a7b35e76cd17b53e57ea9f212470e4d mature?
(I.e. no unforeseen side effects, etc?)

**Comment by andrei-drexler** [comment]
*Mature* is probably not the first word that comes to mind, since it's basically a hack for an unforeseen situation itself, but it should be pretty safe :) If needed, though, we can lower the 8 unit threshold to restrict the side effects even further. And speaking of hacks, I've also committed https://github.com/Novum/vkQuake/commit/e1c892010c4e3afc156703469530335a983b50c2 - I don't expect it to have any ill effects, either, but with so many maps/mods out there, it's hard to say for certain.

**Comment by sezero** [comment]
Applied the the two patches to QS.

Is this issue fixed now?

**Comment by andrei-drexler** [comment]
Only partially, I think:
- the pitch-black models above the grates are now lit as expected (as are the candles in the hub map), but there might be other instances where models appear dark simply because their origin happens to fall right above a dark spot, even if the overall light intensity in that area is higher. This seems to be the case in this screenshot from @Flecked42:
![](https://user-images.githubusercontent.com/90434262/132995868-caae3a95-e514-4a18-874c-1ecb2e55cb44.png)
We could do several spaced-out traces (instead of 1) and average their results, but that might get expensive. A Q3-style lightgrid would be cheaper, but also probably outside the scope of vkQuake/QS.
- translucent surfaces (e.g. water) are still a problem; since their number is usually pretty low I think they could be radix-sorted by depth before rendering without affecting performance too much. Going by the cvars it exposes, the Kex engine seems to uses OIT.
- the disappearing pipe faces are apparently a vis error - they render correctly with `r_novis 1` (which is effectively what the Kex engine does). If I were to hazard a guess, I'd say the mapper placed a `skip` brush around them instead of `clip`.
![vispipes](https://user-images.githubusercontent.com/5121829/134131428-a58d65db-750d-46a5-9a26-076d35c5a06d.gif)
- the flickering lights on the rotating gears in the mg1 hub look like a vkQuake bug (not present in QS) - the fireball is too far away to have an influence:

https://user-images.githubusercontent.com/5121829/134135517-1bfad278-d27d-4b8f-9dcf-fbddccb6e42b.mp4

https://user-images.githubusercontent.com/5121829/134135372-7a585934-c0af-4c9c-9997-fb4cb44c6455.mp4

**Comment by Flecked42** [comment]
The invisible pipes seem to be surrounded by clip brushes since you can shoot through it, but still strange its a vis issue.

**Comment by sezero** [comment]
We shouldn't bother ourselves with a vis issue

**Comment by Novum** [comment]
@sezero Can this issue be closed now?

**Comment by sezero** [comment]
From y point of view, yes. Closing.
