### ISSUE TITLE
YPOD crash

### ISSUE THREAD

**Issue by mdvhimself** [Novum/vkQuake#368]
the mod is famous of its weird texture bugs, but at least ran smoothly with the last version. if you have the time please fix it. might crash some other older maps too. thank you.
https://doom.fandom.com/wiki/Your_Path_of_Destruction

![kép](https://user-images.githubusercontent.com/13852027/132916566-c2ece9e5-fdba-406d-ac8d-ff32a40bf746.png)

**Comment by Novum** [comment]
Nothing was changed in the texture code, so I'm pretty sure this is bogus.

**Comment by mdvhimself** [comment]
sorry, the last version that works is **1.10.0-beta1**

**Comment by mdvhimself** [comment]
![kép](https://user-images.githubusercontent.com/13852027/132936479-e1cacad8-9c61-49ad-9e9b-a000c6b0676c.png)

to be specific, hud looks like this on 1.10.0-beta1
but everything OK on 1.05.3

**Comment by Novum** [comment]
That makes more sense. It's very likely related to the CSQC HUD support.

**Comment by andrei-drexler** [comment]
Fixed in https://github.com/Novum/vkQuake/commit/5f209070d5deb6d28b9d7d39145a49b6fa31f182. The error condition was flipped - the message said 'truncated', but the check was for *extra space* after the image data, which is benign. And yes, this was indeed part of the CSQC HUD support [commit](https://github.com/Novum/vkQuake/commit/4993ee35de5f139e3b44b1db3edbdb5d3be20c6d#diff-b367d7a287aa77ed34a7438a7a9c2d3472d9993751ab73d8118d1794ef2e9d54R240), and it looks like the bug is still there in [QSS](https://github.com/Shpoike/Quakespasm/blob/c48c4f2641f94089327b9136ef9b17d5f7a10b3c/quakespasm/Quake/gl_draw.c#L246).
