### ISSUE TITLE
[Feature Request] Add back r_shadows

### ISSUE THREAD

**Issue by NineKain** [Novum/vkQuake#385]
I know Novum doesn't like them, but I think they can be a nice addition, turned off by default, and they shouldn't be too hard to add back from QSS, I think it should be considered, it's the only thing that's keeping me from making the change completely to vkQuake, please consider.

**Comment by Flecked42** [comment]
> I know Novum doesn't like them

Probably for good reason, they look bad imo and are glitchy.

**Comment by Novum** [comment]
No.

**Comment by Calinou** [comment]
Raytraced dynamic light shadows were added in https://github.com/Novum/vkQuake/pull/611. The feature is enabled by default, but it requires a GPU with hardware accelerated raytracing and does not affect static lights (as the engine doesn't know their direction).

I suppose a FTEQW-style blob shadows option could be added to further complete the effect, so that dynamic objects look more "grounded" if there are no dynamic lights around them.

**Comment by Novum** [comment]
No.
