### ISSUE TITLE
r_scale uses linear scaling instead of nearest-neighbor

### ISSUE THREAD

**Issue by TheParadoxBox** [Novum/vkQuake#393]
It's all in the title. A quick comparison between QS proper and vkQuake will show that scaling with r_scale is much blurrier in vkQuake, probably due to a sub-optimal filtering mode.

**Comment by Novum** [comment]
By design. It's not linear, it's pixel proper area supersampling. This has come up a couple times, but I have no plans right now to implement the shittier version that people seem to like.

**Comment by thekovic** [comment]
@Novum The reason why people like the "shitter" version is because despite the modern API used in the source port, the game is still from 1996 and some people like the pixelated look because it's more retro. Setting r_scale to 4 (or even 8, especially on a 1440p/4K screen) lets them simulate that look while getting the benefit of pushing hundreds of frames on even the largest of maps. Or at least, it would, in theory, if the current implementation in vkQuake didn't turn the image into a blurry mess. Yes, the image is more stable during movement but it also looks like you smeared vaseline over the display, instead of getting that clear, chunky DOS look.
I hope this comment gives you a better understanding of who the people that keep asking for this are and why they are doing so and why the current implementation doesn't excite them. They're not stupid for not liking it, they don't like it because it gives them the exact opposite of what they're trying to achieve when they set r_scale to 4/8. And I'm not saying to throw the current implementation into the bin, I just hope you could add a way to make the image pixelated again and hide it behind a convar or something for those who are really looking for it.

**Comment by QUINTIX** [comment]
Wait a bloody minute. Did novum implement SSAA in software?

_reads through screen_effects.inc_

wow... they basically did. I'm not sure if I should be dismayed or impressed.
