### ISSUE TITLE
Compilation failure of macOS target

### ISSUE THREAD

**Issue by alexey-lysiuk** [Novum/vkQuake#482]
Since the recent changes related to use of `_Generic`, macOS target fails to compile.
```
gl_model.c:542:13: error: controlling expression type 'long' not compatible with any generic association type
                        pixels = q_max (0, (mod_base + l->fileofs + l->filelen) - pixels_p);
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./common.h:88:30: note: expanded from macro 'q_max'
#define q_max(a, b) _Generic((a) + (b), \
```
There are a few other places of the same error.
```
menu.c:1683:33: error: controlling expression type 'unsigned long' not compatible with any generic association type
menu.c:1683:33: error: controlling expression type 'unsigned long' not compatible with any generic association type
host_cmd.c:1035:30: error: controlling expression type 'unsigned long' not compatible with any generic association type
pl_linux.c:70:10: error: controlling expression type 'unsigned long' not compatible with any generic association type
```
Here is the [full compilation log](https://github.com/alexey-lysiuk/vkQuake/runs/6736708796) at 85cda69eb22de2a7361a8b7eb1ca42b9f36b2382.

**Comment by Novum** [comment]
I can't fix this as I don't have a mac. Also this is a compiler issue, all integer sizes are explicitly listed in the _Generic expression.

**Comment by alexey-lysiuk** [comment]
There are no `long` and `unsigned long` types in association lists of `q_min` and `q_max` macros.
At the same time, there is no guarantee that `int64_t` and `uint64_t` are `typedef`'s of `long`.

**Comment by andrei-drexler** [comment]
Should be fixed in 9c22b1aeca12798deef7fad8fec795c99b632cb4.

**Comment by alexey-lysiuk** [comment]
It works. Thank you.

**Comment by sezero** [comment]
I plan to use a different approach to the q_min/q_max/clamp macros problem
by not forcing a c11 feature but by using a gcc-specific way, like:
```c
#if defined(__GNUC__)
/* min and max macros with type checking */
#define q_max(a,b) ({           \
    const __typeof(a) a_ = (a); \
    const __typeof(b) b_ = (b); \
    (void)(&a_ == &b_);         \
    (a_ > b_) ? a_ : b_;        \
})
#define q_min(a,b) ({           \
    const __typeof(a) a_ = (a); \
    const __typeof(b) b_ = (b); \
    (void)(&a_ == &b_);         \
    (a_ < b_) ? a_ : b_;        \
})
#define CLAMP(_minval, x, _maxval) ({           \
    const __typeof(x) x_ = (x);                 \
    const __typeof(_minval) valmin_ = (_minval);\
    const __typeof(_maxval) valmax_ = (_maxval);\
    (void)(&x_ == &valmin_);                    \
    (void)(&x_ == &valmax_);                    \
    (x_ < valmin_) ? valmin_ :                  \
    (x_ > valmax_) ? valmax_ : x_;              \
})
#else
[old stuff]
#endif
```
The new macros are type checking and emit suitable compiler warnings, so
I changed several places to comply mostly by changing several double type
constants into floats along with some others. Here is the patch I plan to
apply to quakespasm: [03-patch.txt](https://github.com/Novum/vkQuake/files/8837482/03-patch.txt)
Can you guys review? Any gotchas, possible issues?

Also: We have this `Q_rint` macro in mathlib.h as:
`#define Q_rint(x) ((x) > 0 ? (int)((x) + 0.5) : (int)((x) - 0.5))`
Isn't that actually C99 `lrint` ?  (Or `lrintf`, where one can actually
use 0.5f along with a float argument instead of 0.5). Am I correct?  If
so, how about using lrint and lrintf here, e.g. this patch:  [09-patch.txt](https://github.com/Novum/vkQuake/files/8837488/09-patch.txt)

A possible source of problem with the lrint patch is that it is changing
MSG_WriteCoord16, MSG_WriteCoord, MSG_WriteAngle and MSG_WriteAngle16 to
operate on floats instead of doubles: Can it result in any issues?

CC: @ericwa

**Comment by andrei-drexler** [comment]
Using GCC's statement expressions when supported sounds like a potential source of bugs down the line, since arguments would get evaluated just once when compiled with GCC and multiple times with MSVC.

As for `Q_rint`, I'd just convert it to a static inline function taking a double.

**Comment by sezero** [comment]
> Using GCC's statement expressions when supported sounds like a potential source of bugs down the line, since arguments would get evaluated just once when compiled with GCC and multiple times with MSVC.

Evaluate-once _is_ the idea actually: is there any point in any of those macros' use
that require multiple evaluation? (And, don't the c11 macros here also evaluate their
args once? I can add an else-if case for c11 though.)

> As for `Q_rint`, I'd just convert it to a static inline function taking a double.

As in always use double? Really needed?

Use of lrint() is OK though, yes?

**Comment by andrei-drexler** [comment]
I realize that single evaluation is the point, and it's great that it's possible in GCC, but the inconsistency between compilers is a major issue IMO. My objection is not about multiple evaluation ever being useful, but rather about the danger of significantly different behavior depending on the compiler used.

> As in always use double? Really needed?

Only needed if you want to have a single version of the function, but there could be two (float/double), I guess. There wouldn't be any difference in terms of performance between them on desktop CPUs made in the past decade+, though, and it's not like `Q_rint` is ever used in performance-sensitive code anyway. I like keeping things as simple as possible, which is why I suggested having just one function.

> Use of lrint() is OK though, yes?

It's C99-only, and I'm not sure it's worth complicating the code checking for C99 support instead of just changing the macro to a static inline function.

**Comment by Novum** [comment]
@sezero Do you _really_ have targets that don't have a C11 compiler available? Really curious what the reasoning for sticking to C89 is.

**Comment by sezero** [comment]
> @sezero Do you _really_ have targets that don't have a C11 compiler
> available? Really curious what the reasoning for sticking to C89 is.

If something is actually doable in the c89 way why not do it?  My main
machine is a CentOS 6.10 which _is_ EOL for 2 years, and it comes with
gcc4.4 as its main compiler and QS builds and work just fine on it: if
I can make it work for everyone why not. _And_, if some new feature is
available, then I surely make use of it.

Specific to the topic here: Gcc and its compatibles support those macros
in every version of them (I even tried gcc2.95 and it works), so why not
use them? Then, if c11 is available, I use it too - e.g. new MSVC.

> > Use of lrint() is OK though, yes?
> 
> It's C99-only, and I'm not sure it's worth complicating the code
> checking for C99 support instead of just changing the macro to a
> static inline function.

That question answers itself in our target audience: lrint and lrintf()
may be C99, but every linux (and possibly every unix) and Mac have them
already. If not, I can simply add a HAVE_LRINT define to makefiles, so
those who don't have them can use the old version. For windows, we have
x86 and x64 asm and sse2 instrinsics code for them, so still no problem.

**Comment by ericwa** [comment]
Just an aside, I'd avoid `rint` because it depends on a global rounding mode - another way to have your code break (or break other people's code), and defaults to "banker's rounding" (2.5 rounds to 2, 3.5 rounds to 4): e.g. https://godbolt.org/z/TddMGvbbh

**Comment by sezero** [comment]
> Just an aside, I'd avoid `rint`

Technically `lrint`, but I hear you - but:

> because it depends on a global rounding mode - another way to have your code break

We don't call fesetenv() ?

> (or break other people's code),

How??

> and defaults to "banker's rounding" (2.5 rounds to 2, 3.5 rounds to 4)

That's what our default `(int)(x + 0.5)` intends, no?

**Comment by ericwa** [comment]
> We don't call fesetenv() ?

I don't see any fesetenv in QS or vkQuake

> How??

If some 3rd party code we're using happens to call rint (say stb, or music decoders, etc.) changing the rounding mode will change its behaviour.. I guess you could consider the 3rd party code broken if it's using rint and depending on a certain rounding mode. This is just my hypothetical worrying though.

> That's what our default (int)(x + 0.5) intends, no?

`(int)(x + 0.5)` rounds 2.5 up to 3 and 3.5 up to 4. The bankers rounding rounds 2.5 down to 2, but 3.5 up to 4.

**Comment by sezero** [comment]
> `(int)(x + 0.5)` rounds 2.5 up to 3 and 3.5 up to 4. The bankers rounding rounds 2.5 down to 2, but 3.5 up to 4.

Well, shit.. Ok, lrint goes down the drain.
