### ISSUE TITLE
Tree model not rendered in ad_sepulcher

### ISSUE THREAD

**Issue by TMHKR** [Novum/vkQuake#577]
A minor render issue. The tree model that should appear in an underground secret in ad_sepulcher isn't being rendered.
The collision is there (i.e. I can't pass through the tree), but the model itself is invisible. Not a big deal, but it's here for you to know.
Latest vkQuake x64 (1.20.3) and latest AD (1.81)

![vkquake0000](https://user-images.githubusercontent.com/6874649/200124548-2e63081d-a3d6-4308-9487-d0faa30423e6.png)

**Comment by temx** [comment]
Tree [shows](https://user-images.githubusercontent.com/24851409/200132879-f30b6198-b712-49d2-b41b-cb7f8b7a8c92.png) for me on both 1.20.3 and the current source; we're going to need more information. Did you manually change AD's HUD? If you didn't, the mod is probably not installed correctly.

**Comment by sezero** [comment]
Never noticed until now that it doesn't show in QS either - tried qs versions down to 0.93.2.

**Comment by temx** [comment]
Ah, good point. It doesn't show with `cl_nopext 1`. Are you running with `pr_checkextension 0`? That would explain the missing tree, the missing HUD, and the missing particles.
It's a static model, without the protocol extensions AD stops adding static models after some limit to avoid overflowing the 64K signon buffer. They are supposed to become normal entities, I guess this is an AD bug.

**Comment by TMHKR** [comment]
It seems I have to use the "modern" particle system for the tree to render (saved1 = 0 in AD's quake.rc)
I'm wondering if I can use the "old-school" particles (solid circles) while maintaining "modern" particle support

**Comment by temx** [comment]
OK, I looked into this further. Not-so-good news: the culprit is https://github.com/SimsOCallaghan/ArcaneDimensions/blob/320f1cec4545563e70027450f2d6d4f08f527c69/misc_model.qc#L626..L634
It's actually checking the map name and testing for FTE particles explicitly, I guess to heuristically detect engines without the signon buffer size limit (without this, Quakespasm won't load it using `sv_protocol 999` which AD sets by default, but 666 would have been fine).
"Solutions": Recompile the progs with that commented out and repack it inside `pak2.pak`. Or extract `maps/ad_sepulcher.bsp` and `maps/ad_sepulcher.lit` from `pak1.pak`, rename them and load the renamed level.

**Comment by sezero** [comment]
If nothing to do, close this ticket?

**Comment by TMHKR** [comment]
Yes, you can close this. I used the classic particles in AD because I used QSS before VKQ - the performance was not good with modern particles.

**Comment by sezero** [comment]
OK, closing.
