### ISSUE TITLE
Indirect sorting order problem

### ISSUE THREAD

**Issue by Novum** [Novum/vkQuake#580]
@temx I saw at least one problem in `ad_sepulcher` if noclipping to the SOCK logo:
![image](https://user-images.githubusercontent.com/112222/204193664-550f765a-c00e-4428-8e36-81dc29ea3a45.png)
The transparency order isn't stable.

**Comment by temx** [comment]
Oh! I was hoping levels wouldn't overlap transparent water world polys since there's no control over what the BSP compiler does. Ironwail has the same problem (with `r_oit 0`), I never noticed.

Options are:
* ignore it
* draw transparent water in direct mode, using a list of potentially transparent surfs built at load time. This shouldn't hurt performance too much as long as there aren't too many water surfs, but it's another special case.
* serialize IB construction for water (impractical?) or sort the indices (difficult, will cost GPU time)
* implement OIT

I can do the 2nd one if you think this should be fixed.

**Comment by Novum** [comment]
What OIT does Ironwail use? Linked lists per fragment? That's very slow as far as I know.

**Comment by temx** [comment]
5f2a4ee should take care of this, now anything transparent should be drawn in the same order as before (no exception for opaque water, sadly).

> What OIT does Ironwail use? Linked lists per fragment?

No, it's weighted blending. It uses a single R16G16B16A16 buffer with ADD blending mode which contains the sum of all transparent fragments (weighted by a function of the alpha value itself and the distance), resolve is dividing by alpha (which contains the sum of weights). Another R8 buffer contains the total "revealage" to blend with the opaque pass. It does look a bit strange at times ([off](https://user-images.githubusercontent.com/24851409/204401714-e4b33876-9588-48cb-991a-086a3bef0696.png), [on](https://user-images.githubusercontent.com/24851409/204401720-b9fcc5d9-4e78-4e61-9f33-3e2f3a5c72fe.png); [off](https://user-images.githubusercontent.com/24851409/204401928-9d78cbb6-0f4a-48e9-b101-7912f8d4c2d5.png), [on](https://user-images.githubusercontent.com/24851409/204401936-2916b132-2f14-4574-b271-fe1a61bc3a77.png); [off](https://user-images.githubusercontent.com/24851409/204401944-ce14b589-eb8e-43f0-8ff4-e4aade79026e.png), [on](https://user-images.githubusercontent.com/24851409/204401961-c5cf54c2-1d86-41a6-947d-9f3f8a2a9aad.png)). I think it's based on https://jcgt.org/published/0002/02/09/ It's a recent addition, it's not in 0.6.0.

**Comment by Novum** [comment]
Thanks for the fix!
