### ISSUE TITLE
v1.31: Held keyboard presses don't persist on map change (after entering a slipgate)

### ISSUE THREAD

**Issue by RavenMacDaddy** [Novum/vkQuake#695]
**Describe the bug**

If for example I hold **W** to keep moving forward after entering a slipgate, I will just stand still, cause held keys aren't persisted (i.e., don't register/get read) in this new version (1.30.1 vs 1.31) — which just feels awkward, and hopefully some weird regression or bug.

I've confirmed that the older, referenced version, doesn't exhibit this behaviour.

**To Reproduce**

1. Start a new game.
2. Choose whichever difficulty.
3. Enter a slipgate; I simply went with the first episode. 
4. Notice how any input that was being held (unconfirmed if this applies to other input methods like mouse or controller) isn't being registered.

**Expected behaviour**

For held keys to register on map change, e.g., **W** for moving forward

**Desktop (please complete the following information):**
 - OS: Windows 11 - 23H2
 - NVIDIA GTX 1080
 - Driver version: 555.99

**Comment by vsonnier** [comment]
Hello @RavenMacDaddy the change was intentional, brought by :   

* Clear button status on map load to prevent stray fires/jumps

Reverting that commit would bring back v1.30 behaviour. 

Now a Sipgate as in Hub / ExNx is really a map change, disguised as a simple teleporter. 

Normal teleporters works as usual, without affecting player movement of course.

The goal of the commit was really to reset  the player momentum when it enters a completely unknown area. 

I'm reluctant to revert this change, there are good reasons behind this  I think. 

Maybe hiding the new behaviour behind yet another CVAR ? I would rather revert everything to the v1.30 way to keep things simple...

**Comment by RavenMacDaddy** [comment]
I appreciate the explanation, whatever you decide is best.

**Comment by vsonnier** [comment]
I agree on the ackwardness of being cut-off for the previous movement, I feel it too to be honest. 

The way I see things, if there are enough complaints about the new behaviour, reverting it for a v1.31.1 is very easy.

**Comment by vsonnier** [comment]
Right; _I_'ve made a descision, considering the pros and cons:
- Cons : on map change, you need to re-apply your movement. That is only relevant if the maps are intended to be loaded seamlessly, hiding a load behind a Slipgate. This is not very common I think, even if the very Quake hub is a counter-exemple
- Pros : For all the cases were a level ends with a Score board, and a 'Loading' plaque, this is certainly unexpected to continue the previous movement starting the new level. Good exemples are Quake levels within an Episode.

I think the latter point weigh more thant the first, and was the reason for the change.

Let's put that in the 'wontfix' category.
