### ISSUE TITLE
Crash with RT shadows enabled on newest AMD Drivers

### ISSUE THREAD

**Issue by dumbcatposter** [Novum/vkQuake#710]
**Describe the bug**
Upon starting the game normally, the game tries to load the attract mode demo and crashes to desktop. I built the project from source in Visual Studio and narrowed it down to a stack overflow in r_brush.c:2318.  Just to be safe I DDU'ed my drivers and reinstalled them to no avail.

**To Reproduce**
- DDU display drivers
- Install latest AMD Adrenalin software from AMD
- Start the game
- Ouchie

**Expected behavior**
The game loads maps without crashing.

**Screenshots**
![Screenshot of the Call stack](https://github.com/user-attachments/assets/e9f0d6f2-c869-4a40-9223-b83f3271f7f4)

**Desktop (please complete the following information):**
 - OS: Windows 11
 -  AMD Radeon 7900 XTX
 - Driver version 24.6.1, Vulkan instance version 1.3.261

**Mod**
Vanilla Quake, Steam release

**Comment by vsonnier** [comment]
Looks like, by all looks a driver bug : given the past effort to have a clean Vulkan usage, this is very unlikely that new driver has triggered a yet undicovered bug on the vkQuake side.

I've no mean to reproduce anyway being in either Intel / Nvidia, we need a competent AMD user here.

**Comment by dumbcatposter** [comment]
If I add `r_rtshadows 0` to my autoexec.cfg, the game does indeed launch correctly. Weirdly enough, if I turn the dynamic shadows back on afterward, the game doesn't crash.

**Comment by Novum** [comment]
I would keep this open, the validation layers aren't that great with RT right now, maybe there is some invalid usage.

**Comment by vsonnier** [comment]
User @thesockninja  reported in #714, (duplicate) : 

----
vkQuake.exe will open a console window for about two seconds, appear to be hunting for a file or driver, and immediately close without an error displayed. Window is not open long enough for me to read what it says.

**To Reproduce**
Attempt to open vkQuake.exe after installing in both ways:

Drag / drop installation utilizing [vkQuake-1.31.0_win64.zip](https://github.com/Novum/vkQuake/releases/download/1.31.0/vkQuake-1.31.0_win64.zip) into directory structure: C:\users\ (username)\Desktop\vkQuake - vkquake files are all here, with an id1 subdirectory inside with PAK0/PAK1 files pulled from either the Nightdive rerelease (Steam) or an OG Quake CDrom install.

Attempting to open vkQuake.exe after installation using [vkQuake-Installer-x64-1.31.0.exe](https://github.com/Novum/vkQuake/releases/download/1.31.0/vkQuake-Installer-x64-1.31.0.exe) and pointing to the same sourced PAK files (keeping them in the Steam subdirectory) produces the same situation 

**Expected behavior**
vkQuake.exe will load from PAK files and start the attract mode / game menu.

**Screenshots**
This is a recent crash in Windows Event Viewer:

![image](https://github.com/user-attachments/assets/b8975e8b-bd83-413e-9387-ba6be034e75b)

I have attached the associated WER file as well as associated vkQuake crash dump found in C:\Users\(USER)\AppData\Local\CrashDumps in:

[vkQuakeBugReport.zip](https://github.com/user-attachments/files/16402229/vkQuakeBugReport.zip)

**Desktop:**
7800x3d
ASrock B650 Livemixer
32GB DDR5-6000 @ 36cl or so
1000w EVGA PSU
1TB Crucial M.2 / NVME (Install Drive / C:)
 - OS: Windows 11
 - GPU: Powercolor Hellhound AMD 7900xtx (stock configuration)
 - issue persists similarly on 24.6.1 and 24.7.1

**Mod**
Nightdive rerelease sourced (classic, rerelease) PAK files, also tried with PAK files sourced from a Quake retail CD, no other mods.

**Additional context**
I did read [this bug report](https://github.com/Novum/vkQuake/issues/710), however, I am not sure what "If I add r_rtshadows 0 to my autoexec.cfg, the game does indeed launch correctly." entails specifically or where to perform similar actions for a testable fix.

No issues with any other programs, crashes, or bluescreens. Other sourceports work with the same PAK files. I have a second computer (10700k, RX580 using 24.6.1 and also 24.7.1 later as I was troubleshooting, Windows 10) where this install structure, 1:1 same sourced files, works fine.

Attempted a complete reinstall of the 64-bit vkquake files with both the installer and the raw files. I attempted uninstalling using both windows uninstaller and Wise Program Uninstaller to remove prior, no change in any regard. (This is the cleanest uninstallation method that I can find. If there is a better one, please advise.)
Attempted running vkQuake.exe as administrator, no change.
Uninstalled (w/ DDU) video drivers, reinstalled, no change.
Updated from 24.6.1 to 24.7.1 and both drivers produce the same issue.
No settings in the 7900xtx different than the RX580 as far as I can tell from AMD Adrenalin Software.

Please let me know if anything else is needed.

**Comment by thesockninja** [comment]
I was also able to do the following to produce a fix:

"Well, simply create a text file autoexec.cfg in your id1 directory and put the line r_rtshadows 0 in it. Now if you start vkQuake, RayTracing Shadows will be disabled."

**Comment by tdimarzio** [comment]
I believe I am seeing this as well. 7900 XTX (drive 24.7.1). If i go back to vkQuake-1.22.3_win64 then it loads fine / no problems. Everything after (vkQuake-1.30.0_win64, vkQuake-1.30.1_win64, vkQuake-1.31.0_win64, vkQuake-1.31.1_win64) = instant crash on load. I have no other crashes or instabilities in any other game or 3D application I use. If I add "r_rtshadows 0" to autoexec.cfg then the crash goes away.

**Comment by vsonnier** [comment]
Changed the titile to mention RT shadows, since it seems to be the problem here.

**Comment by Novum** [comment]
I did review the code and didn't see any obvious issues. Latest validation layers also report none.

**Comment by tdimarzio** [comment]
This is no longer occuring in vkQuake. rtshadows set to 0 workaround is no longer required. I assume this issue can be closed. Unfortunately, I don't know which driver version or vkquake version it started working in. I am currently running AMD driver 24.10.1 and vkQuake 1.31.3

**Comment by vsonnier** [comment]
Thanks @tdimarzio for the report ! `1.31.2` received Vulkan fixes by @Novum, so perhaps that fixed it... maybe combined with recent drivers, who knows ?

Anyway that is a good thing to have RT shadows working at last.
