### ISSUE TITLE
Invisible Dynamic Objects on Steam Deck/Linux via Luxtorpeda

### ISSUE THREAD

**Issue by Duffking** [Novum/vkQuake#717]
When playing vkQuake on Steam Deck via Luxtorpeda, dynamic objects such as switches, doors, some pickups are all invisible. For example, on Entryway after picking a difficulty, the staircase down to the endboss is visible as the floor is completely invisible.

**To Reproduce**
- Install Luxtorpeda (I used ProtonUp-QT from the discover store)
- Set Quake in Steam to use Luxtorpeda as the compatability layer instead of proton
- In the Luxtorpeda menu that appears after launching the game, select vkQuake or vkQuake remaster
- Start a new game and select a difficulty
- Observe the floor is missing

**Expected behavior**
- Dynamic objects etc are all visible

**Screenshots**
https://i.imgur.com/LIYpdF2.jpeg

**Desktop (please complete the following information):**
 - OS: Steam Deck/Arch
 - GPU/Driver: Unsure, Steam Deck latest?

**Mod**
Base Quake

**Additional context**
I previously raised this issue with Luxtorpeda's developers [here](https://github.com/luxtorpeda-dev/packages/issues/1274#issuecomment-2241393292), and they were able to reproduce but weren't sure what to do about it and suggested raising here instead. A terminal log is attached there, or you can see it here: https://pastebin.com/sVJ3NTX1

**Comment by vsonnier** [comment]
Hello @Duffking,

Sorry but there is nothing usefull in this log that can be vkQuake-related.

Since the developpers themselves are able to reproduce, this is up to them to debug or at least provide mainingful tracbacks and such for us.

I'm leaving this open for some tome to see if someone having a Steam Deck have the motivation to investigate further... However, if nothing new shows up, I'll close it.

**Comment by d10sfan** [comment]
I'm the developer of luxtorpeda, what sort of information would be helpful to help diagnose this? I'm not sure of anything this could be from my end since I'm just compiling the latest version of this project but there may be some library problem or something.

Note that this version works fine on desktop so it seems isolated to steam deck.

I can try the app image on my steam deck and see if that replicates it. If it does that points to an issue with the code somewhere

**Comment by d10sfan** [comment]
The same issue happens with the AppImage provided here, so this is not directly related to luxtorpeda, but something wrong with vkquake and the steam deck.

Let me know of anything that me or another steam deck user could provide to help debug this problem.

**Comment by d10sfan** [comment]
Note that ironwail works fine on the steam deck, but not sure if that helps or not.

**Comment by SorayaProtera** [comment]
Having the same issue on the Steam Deck OLED, with both the AppImage and the Windows executable run through the Proton compatibility layer. The issue occurs regardless of whether it's being launched through Steam.

I'm not sure it will help, but I'm attaching a screenshot of the first obvious problem in e1m1, and the terminal log. Oddly, while ammo pickups and movable walls were invisible, the armor pickup in the starting area was visible. 

it's simple to reproduce, so please let me know if there's any other information I can provide.

[vkquake e1m1 output.txt](https://github.com/user-attachments/files/16716915/vkquake.e1m1.output.txt)
![vkquake0000](https://github.com/user-attachments/assets/c5fc80bb-aa4b-4605-8bc6-00c8086d8d46)

**Comment by vsonnier** [comment]
It has reported in #732 that now it is working on Steam Deck. So, is there still a problem for Steam Deck/Linux via Luxtorpeda ?

**Comment by Duffking** [comment]
Hello - just gave it a try and it's looking good now :)

**Comment by vsonnier** [comment]
Thanks for the report !
