### ISSUE TITLE
Taking screenshots occasionally crashes with Vulkan error

### ISSUE THREAD

**Issue by bubbleguuum** [Novum/vkQuake#747]
System:

- vkQuake 1.31.3
- Windows 11 24H2
- NVIDIA RTX 4080S, driver 566.03

Taking screenshots with F12 sometimes crashes with either `vkQueueSubmit failed` or `vkDeviceWaitIdle failed` error dialog.

To reproduce it, hit F12 possibly several times and fast until it eventually crashes.

**Comment by vsonnier** [comment]
Maybe it is similar to https://github.com/Novum/vkQuake/issues/715 ... Did it work with `Prefer layered on DXGI Swapchain` setting ?

**Comment by bubbleguuum** [comment]
It still crashes with forced `Prefer layered on DXGI Swapchain`. 

I have a hard time triggering this crash on the base game's start map, although I could make it crash once or twice here.

However I can trigger it very easily in a quick a save of the Immortal Lock that I have attached (rename to .sav).

[quick.txt](https://github.com/user-attachments/files/17715363/quick.txt)

To reprod:

- put quick.sav in immortal sub-folder
- start vkquake
- switch to immortal mod
- F9 to load the quick save
- hit F12, possibly a few times after moving in the level

**Comment by andrey-budko** [comment]
I can easily reproduce this issue from the provided savegame, but it happens only with r_indirect set to 1 (which causes a lot of other bugs for me).

Win10, GT 710 GPU, driver 456.71 (default drivers installed by windows, this is not a gaming PC)

**Comment by vsonnier** [comment]
> However I can trigger it very easily in a quick save of the Immortal Lock that I have attached (rename to .sav).
[quick.txt](https://github.com/user-attachments/files/17715363/quick.txt)
To reprod:
put quick.sav into immortal sub-folder
start vkquake
switch to immortal mod
F9 to load the quick save
hit F12, possibly a few times after moving in the level

Cannot reproduce on my side, even spamming F12 like crazy (creating 50+ screenshots). Here are my configs for reference:
[vkQuake_immortal_configs.zip](https://github.com/user-attachments/files/17721009/vkQuake_immortal_configs.zip)

My typical GPU settings in NVIDIA control Panel are:
- FXAA = off
-  Anisotropic = 8x (forced)
- Negative LOD = Fixed
- Anisotropic optimization = On
- Texture filtering = Quality
- Trilinear optimization = On
- Low latency = off
- Power management = Maximum performance
- MFAA = off
- Presentation method vk/OpenGL = DXGI chain
-  Max FPS = off
- Threaded optimisation = on
- Vsync = off

@bubbleguuum Instead of using a third party tool with bizarre side-effects, did you try to combine Nvidia driver settings like Vsync off / Adaptative ? + Max FPS for instance ?

**Comment by bubbleguuum** [comment]
Well I've made different test with a mix of in-game settings and NVIDIA CP settings. RTSS disabled so it does not interfere with framepacing. I also kept "DXGI swapchain" to "Auto" for all these tests.

The results are a bit puzzling and the fact that there are many factors at play make it quite complex to test and understand.

1. With G-Sync enabled, the only way to have no tearing nor input lag is: 

- in-game v-sync off
- cap framerate to 59 with either one of these methods:
    - in the NVIDIA Control Panel "Max fps" setting
    - with RTSS
    - and yes, in vkquake, by setting `host_maxfps 59`. The UI does not allow to set it to 59 as it only has +10 increments. Maybe something to consider

=> Any setting of "Low latency Mode" (LLM) does not help to get rid of input lag, only framecapping to 59 (anything below monitor refresh rate) helps.

2. Next, I checked if I could find a combination of settings that works with in-game v-sync on, and not resulting in massive input lag and/or tearing.

With G-Sync enabled, that seems absolutely impossible. With G-Sync disabled, it is possible with these settings:

- in game vsync on
- in game max fps = 60

But there are 2 caveats:

- ALT+TAB breaks frame times (see next paragraph) so when you get back to the game there is input lag
- the first time you set in-game max fps to 60, you have to set it from lower values (that is from 50->60). If you set it from 70->60 frametimes are messed up.

Speaking of frametimes, each and every time I observed input lag and/or tearing, the frametime graph shown by RTSS overlay was very spiky with some frames taking 0.2ms, other 16.6ms and other 33.3ms (approxmatively): imagine the frametime graph looking like a filled rectangle !  When there is no issue, the graph is a flat line with each frame taking exactly 1/59 seconds (G-Sync enabled) or 1/60 second (G-Sync disabled).

If it all seems very confusing and hard to understand, it is. Each time I had to double check my finding to make sure it is correct.
Moreover, proper framepacing with vulkan vs vysnc and in general on a variety of setup seems to be a common and complex topic if you Google it. In my experience, OpenGL has less issues with this.

**Comment by Novum** [comment]
`host_maxfps` defaults to 200

**Comment by Novum** [comment]
https://github.com/Novum/vkQuake/commit/40cdc6f718d0b2b8174f56ef41c7f5e9ded1ff89

There is a good chance this fixes it.

**Comment by bubbleguuum** [comment]
Thanks for the fix.

What about allowing +1 and -1 increments in the UI for `Max FPS` (`host_maxfps`) ?
And eventually a hard cap at 1000 fps to avoid coil whine ?

**Comment by vsonnier** [comment]
> And eventually a hard cap at 1000 fps to avoid GPU coil whine ?

We can keep the "no limit" setting on the left hand side.  Simply go to the opposite scale, it is already clamped to 1000 fps in the interface. 

> What about allowing +1 and -1 increments in the UI for Max FPS (host_maxfps) ?

It would be more convenient to add a slider for  max fps with this level of increment, bringing the "slider with displayed value" feture from recent QS. 
I have not considered bringing it in before, because I thought of very little value but that may be a good case for it.

**Comment by bubbleguuum** [comment]
It's great that on the right side it is already limited to max 1000 fps, which I did not know.

But let's consider a player that go into the setting and set the max fps to uncapped, because this is what he does in every other game. He has a high end GPU and now is getting 2000+ fps and (probably) coil whine and high GPU wattage (150W+ observed here on my RTX4080S uncapped). Two possibilities: he immediately notice coil whine, link it to the uncapped fps and undo his choice to something more reasonable. Or he leaves it as this, not knowing better. Since there are no monitor capable of 1000+ Hz, I think it would be a good idea to also cap "no limit" to 1000 Hz (or whatever max "max fps" is allowed in the future).

IIRC, 1 or 2 years ago, there has been a game (an Amazon one I think) that had very high uncapped framerates in its UI that caused problems to GPUs.
