### ISSUE TITLE
Fallback/alternative to USCALED formats

### ISSUE THREAD

**Issue by SaschaWillems** [Novum/vkQuake#98]
The [alias pipeline](https://github.com/Novum/vkQuake/blob/ce5fd12fa62e72039073fd6982867ba5cf8751de/Quake/gl_rmisc.c#L1568) uses the VK_FORMAT_R8G8B8A8_USCALED for some input attributes.

That format is not supported on all platforms (e.g. the Samsung mobile I'm currently debugging on), so I guess a fallback would make sense, or revert to _UNORM (if possible) as that's supported pretty much everywhere.

**Comment by Novum** [comment]
It's not that simple. USCALED means the vertex shader gets an input from 0.0f - 255.0f for that attirbute, UNORM means 0.0f-1.0f

**Comment by Novum** [comment]
Okay, first I didn't understand why everything isn't just 255 times smaller. You "get lucky" because the W component also gets scaled to 1.0f / 255.0f which then scaled back the models in the perspective divide.

But the fog still breaks with UNORM because the distance calculation is wrong.

I will do a proper patch.

**Comment by Novum** [comment]
Fixed by 795f4bf7018de73ad867befa551909f015e984c8
